# -*- coding: utf-8 -*-
"""Operações Aritmeticas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2ZlTxcp2MXONQqj72_ZNXI5OgOU1PIs
"""

import cv2 as cv
from PIL import Image
import numpy as np
import requests
import io
from google.colab.patches import cv2_imshow


# URL da imagem que será usada
url_imagem = "https://img.freepik.com/vetores-gratis/modelo-de-adesivo-com-uma-unica-casa-isolada_1308-64529.jpg"

# Fazendo o download da imagem
resposta = requests.get(url_imagem)

nome_imagem = "imagem.jpg"

if resposta.status_code == 200:
    # Usando BytesIO para carregar a imagem diretamente em memória
    imagem = Image.open(io.BytesIO(resposta.content))

    # Pegando as proporções da imagem original
    largura_original, altura_original = imagem.size

def operacoes_aritmeticas():
    print("\nOperações aritméticas!")

    # Solicitando o valor para adição/subtração
    valor_operacao = int(input("Digite o valor para adição/subtração (entre 0 e 255): "))

    # Menu para escolher entre adição ou subtração
    print(20*"---")
    print("Escolha a operação aritmética: ")
    print(20*"---")
    print("1. Adição")
    print("2. Subtração")
    operacao_escolhida = int(input(''))

    # Convertendo a imagem PIL para NumPy para operações com OpenCV
    imagem_np = np.array(imagem)

    # Realizando a operação escolhida
    if operacao_escolhida == 1:
        print("Operação de Adição escolhida!")
        imagem_resultante = cv.add(imagem_np, np.full(imagem_np.shape, valor_operacao, dtype=np.uint8))
    elif operacao_escolhida == 2:
        print("Operação de Subtração escolhida!")
        imagem_resultante = cv.subtract(imagem_np, np.full(imagem_np.shape, valor_operacao, dtype=np.uint8))
    else:
        print("Número inválido. Tente novamente!")
        operacoes_aritmeticas()

    # Exibindo a imagem resultante da operação aritmética
    cv2_imshow(imagem_resultante)

# Executa as operações aritméticas diretamente
operacoes_aritmeticas()